---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
name: fedora-bluebird
description: This image is a fork of Fedora Silverblue for personal use by Birdie.

# image-version can be set to latest or a specific release number
base-image: ghcr.io/ublue-os/silverblue-main
image-version: 44

# module configuration, executed in order
# you can include multiple instances of the same module
modules:
  - type: files
    files:
      - source: system
        # scary
        destination: /

  - type: dnf
    repos:
      copr:
    install:
      packages:
    remove:
      packages:
        - firefox
        - firefox-langpacks

  - type: default-flatpaks
    configurations:
      - notify: false
        scope: system
        install:
          - 
          - 
      - scope: user

  - type: signing